version: '3'

dotenv: ['.env']

vars:
  BUILDER:
    sh: |
      if command -v docker >/dev/null 2>&1; then
        echo docker
      else
        echo podman
      fi

includes:
  containers:
    taskfile: ./Taskfile.containers.yml
  schema:
    taskfile: ./projects/schema/Taskfile.yml
    dir: ./projects/schema
  api-workers:
    taskfile: ./projects/api-workers/Taskfile.yml
    dir: ./projects/api-workers
  frontend:
    taskfile: ./projects/frontend/Taskfile.yml
    dir: ./projects/frontend
  migrations:
    taskfile: ./projects/migrations/Taskfile.yml
    dir: ./projects/migrations

tasks:
  default:
    desc: Build all services
    cmds:
      - task: containers:default
        vars: { BUILDER: '{{.BUILDER}}' }

  tf:
    desc: Run OpenTofu commands (aliases to terraform)
    dir: terraform
    cmds:
      - tofu {{.ARGS | default .CLI_ARGS}}

  tf:init:
    desc: Initialize OpenTofu
    cmds:
      - task: tf
        vars: { ARGS: "init" }

  tf:plan:
    desc: Plan OpenTofu changes
    cmds:
      - task: tf
        vars: { ARGS: "plan" }

  tf:apply:
    desc: Apply OpenTofu changes
    cmds:
      - task: tf
        vars: { ARGS: "apply" }

  local:install:
    desc: Install local dependencies
    cmds:
      - pnpm install
  
  local:build:
    desc: Build all local projects
    cmds:
      - pnpm -r build

  build:
    desc: Build all projects
    cmds:
      - task: containers:build
        vars: { BUILDER: '{{.BUILDER}}' }

  start:
    desc: Start all services
    cmds:
      - task: containers:start
        vars: { BUILDER: '{{.BUILDER}}' }
  
  stop:
    desc: Stop all services
    cmds:
      - task: containers:stop
        vars: { BUILDER: '{{.BUILDER}}' }

  install:
    desc: Install dependencies and build all projects
    cmds:
      - cmd: pnpm install