version: '3'

dotenv: ['.env']

vars:
  BUILDER:
    sh: |
      if command -v docker >/dev/null 2>&1; then
        echo docker
      else
        echo podman
      fi

includes:
  containers:
    taskfile: ./Taskfile.containers.yml
  schema:
    taskfile: ./projects/schema/Taskfile.yml
    dir: ./projects/schema
  api-workers:
    taskfile: ./projects/api-workers/Taskfile.yml
    dir: ./projects/api-workers
  frontend:
    taskfile: ./projects/frontend/Taskfile.yml
    dir: ./projects/frontend
  migrations:
    taskfile: ./projects/migrations/Taskfile.yml
    dir: ./projects/migrations

tasks:
  default:
    desc: Build all services
    cmds:
      - task: containers:default
        vars: { BUILDER: '{{.BUILDER}}' }

  tf:
    desc: Run OpenTofu commands (aliases to terraform)
    dir: terraform
    cmds:
      - tofu {{.ARGS | default .CLI_ARGS}}

  tf:init:
    desc: Initialize OpenTofu
    cmds:
      - task: tf
        vars: { ARGS: "init" }

  tf:plan:
    desc: Plan OpenTofu changes
    cmds:
      - task: tf
        vars: { ARGS: "plan" }

  tf:apply:
    desc: Apply OpenTofu changes
    cmds:
      - task: tf
        vars: { ARGS: "apply" }

  tf:import:
    desc: Import existing Cloudflare resources into OpenTofu state
    cmds:
      - task: tf:init
      - python3 ./scripts/tf_import_cloudflare.py

  tf:worker:template:
    desc: Render wrangler deploy config from Terraform template output
    cmds:
      - task: tf:init
      - tofu -chdir=terraform output -raw api_worker_wrangler_deploy_toml > projects/api-workers/project/wrangler.deploy.toml

  tf:worker:deploy:
    desc: Render wrangler deploy config and deploy worker from Terraform context
    cmds:
      - task: worker:setup
      - task: tf:worker:template
      - cd projects/api-workers/project && pnpm exec wrangler deploy src/index.ts --config wrangler.deploy.toml
      - rm -f projects/api-workers/project/wrangler.deploy.toml

  local:install:
    desc: Install local dependencies
    cmds:
      - pnpm install
  
  local:build:
    desc: Build all local projects
    cmds:
      - pnpm -r build

  worker:setup:
    desc: Set up API worker project dependencies
    cmds:
      - task: api-workers:setup

  worker:deploy:
    desc: Create API worker deployment artifact
    cmds:
      - task: tf:worker:deploy

  deploy:
    desc: Apply infrastructure, then deploy the API worker with wrangler
    cmds:
      - task: worker:setup
      - task: tf:apply
      - task: worker:deploy

  build:
    desc: Build all projects
    cmds:
      - task: containers:build
        vars: { BUILDER: '{{.BUILDER}}' }

  start:
    desc: Start all services
    cmds:
      - task: containers:start
        vars: { BUILDER: '{{.BUILDER}}' }
  
  stop:
    desc: Stop all services
    cmds:
      - task: containers:stop
        vars: { BUILDER: '{{.BUILDER}}' }

  install:
    desc: Install dependencies and build all projects
    cmds:
      - cmd: pnpm install